ptrkrysik/gr-gsm

- apps/airprobe_rtlsdr.grc
- apps/airprobe_rtlsdr.py
- include/grgsm/endian.h
- lib/decryption/decryption_impl.cc
- lib/misc_utils/bursts_printer_impl.cc
> Define missing 16 bit endian swap macro and fix some endian.h inclusion.

- examples/airprobe_tchf.grc
- grc/demapping/gsm_tch_f_chans_demapper.xml
- grc/demapping/gsm_universal_ctrl_chans_demapper.xml
- include/grgsm/decoding/tch_f_decoder.h
- include/grgsm/demapping/tch_f_chans_demapper.h
- lib/decoding/tch_f_decoder_impl.cc
- lib/decoding/tch_f_decoder_impl.h
- lib/demapping/tch_f_chans_demapper_impl.cc
- lib/demapping/tch_f_chans_demapper_impl.h
> Fix for TCH/F demapper

- grc/gsm_block_tree.xml
- grc/misc_utils/CMakeLists.txt
- grc/misc_utils/gsm_burst_sink.xml
- grc/misc_utils/gsm_burst_source.xml
- include/grgsm/misc_utils/CMakeLists.txt
- include/grgsm/misc_utils/burst_sink.h
- include/grgsm/misc_utils/burst_source.h
- lib/CMakeLists.txt
- lib/misc_utils/burst_sink_impl.cc
- lib/misc_utils/burst_sink_impl.h
- lib/misc_utils/burst_source_impl.cc
- lib/misc_utils/burst_source_impl.h
- swig/grgsm_swig.i
Hi @ptrkrysik , 
this a implementation of 
* a burst sink, which writes bursts to a output file by serializing the corresponding pmt
* a burst source, which reads a file and outputs the bursts, by de-serializing the pmt back. 
There is one issue, I wasn't able find out how to make the flow graph stop after it finished the de-serializing and further processing of bursts. Maybe you have an idea ?
> Implemented a burst sink and a burst source. See issue #42

- grc/demapping/CMakeLists.txt
- grc/demapping/gsm_bcch_ccch_demapper.xml
- grc/demapping/gsm_bcch_ccch_sdcch4_demapper.xml
- grc/demapping/gsm_sdcch8_demapper.xml
- grc/gsm_block_tree.xml
Hi @ptrkrysik , 
here are the preconfigured blocks we discussed in issue #55
> Preconfigured demapper blocks 

- grc/misc_utils/gsm_bursts_printer.xml
- include/grgsm/misc_utils/bursts_printer.h
- lib/misc_utils/bursts_printer_impl.cc
- lib/misc_utils/bursts_printer_impl.h
Hi, 
here are the modifications I made to burst printer as proposed in #86
> burst printer enhancement - option framecount and payload only

- grc/gsm_block_tree.xml
- grc/misc_utils/CMakeLists.txt
- grc/misc_utils/gsm_extract_immediate_assignment.xml
- include/grgsm/misc_utils/CMakeLists.txt
- include/grgsm/misc_utils/extract_immediate_assignment.h
- lib/CMakeLists.txt
- lib/misc_utils/extract_immediate_assignment_impl.cc
- lib/misc_utils/extract_immediate_assignment_impl.h
- swig/grgsm_swig.i
Hi @ptrkrysik, 
here is a pull request for the extractor referenced in issue #84 
I am not sure if you like to have the pull request to master branch, or to romankh-master.
Currently I am creating a new branch in my repo for every feature, so this may be sufficient for testing before merging. Otherwise drop me a note
> Immediate Assignment Extractor

- lib/decoding/tch_f_decoder_impl.cc
Hi Piotr, 
I finally added support for "Channel Mode Modify" messages in the AMR decoder. That enables the decoder to switch to another AMR bitrate automatically on reception of such a message. 
Currently this feature is tested only on akibsayyed's AMR capture.
I will try to get some more AMR captures to test the different modes and also this particular functionality.
> Added handling of channel mode modify messages for AMR

- lib/receiver/cx_channel_hopper_impl.cc
I added some checks for the input values of the CX channel hopper block. When the user inputs a value that is not compliant with the GSM standard, a warning will be printed and the values will be clamped.
> Added input validation to CX channel hopper block

- lib/misc_utils/burst_source_impl.cc
> Fix for burst source thread join() bug. Issue #89

- grc/decoding/gsm_tch_f_decoder.xml
- include/grgsm/decoding/tch_f_decoder.h
- lib/decoding/tch_f_decoder_impl.cc
- lib/decoding/tch_f_decoder_impl.h
See issue #107 for a description
> Noise reduction on TCH-FR

- include/grgsm/endian.h
- lib/qa_utils/burst_sink_impl.cc
- swig/CMakeLists.txt
the title says it all.
It fixes compilation and linking on Mac OS X (and it actually works too! ;-) )
> fix compilation and linking on Mac OS X

- lib/decoding/control_channels_decoder_impl.cc
- lib/decoding/tch_f_decoder_impl.cc
- lib/demapping/tch_f_chans_demapper_impl.cc
- lib/demapping/universal_ctrl_chans_demapper_impl.cc
Fix issue #112 
I reviewed all the blocks, hopefully I didn't miss one
> Fix issue #112 (copy messages instead of modifying the input msg)

- apps/airprobe_rtlsdr_capture.py
- python/CMakeLists.txt
- python/__init__.py
- python/misc_utils/arfcn.py
- python/qa_arfcn.py
Hi @ptrkrysik, 
as discussed in the mailing list ( https://groups.google.com/forum/#!topic/gr-gsm/6yDRRGNXD4g), here comes the first app, no giant leap:
* added support for arfcn calculation
* app itself takes either frequency or arfcn as param
* either saves capture to cfile or burst file, or both
* Option -v prints the captured bursts to provide user with feedback that there are bursts that are captured
> App for RTL-SDR single channel capture

- apps/airprobe_decode.py
Hi Piotr,
here comes the decoder app....
Best regards, 
Roman
> Decoder app

- apps/airprobe_decode.py
- grc/misc_utils/gsm_message_printer.xml
- include/grgsm/misc_utils/message_printer.h
- lib/misc_utils/bursts_printer_impl.cc
- lib/misc_utils/message_printer_impl.cc
- lib/misc_utils/message_printer_impl.h
Hi Piotr, 
here is a pull request for issue #127 
Additionally I changed burst_printer such that it uses libosmogsm function for frame count calculation, and fixed a minor issue in airprobe_decode (arfcn or freq were mandatory for burst input files, which is not necessary).
> airprobe_decode enhancements

- apps/CMakeLists.txt
- apps/airprobe_rtlsdr_scanner.py
- include/grgsm/misc_utils/extract_system_info.h
- lib/misc_utils/extract_system_info_impl.cc
- lib/misc_utils/extract_system_info_impl.h
- python/misc_utils/arfcn.py
- python/qa_arfcn.py
Hi Piotr, 
here is the pull request for the rtlsdr_scanner as discussed on the mailing list.
I will add some doc in the wiki soon.
br,
Roman
> Wideband scanner

- grc/gsm_block_tree.xml
- grc/receiver/CMakeLists.txt
- grc/receiver/gsm_wideband_input.xml
- python/CMakeLists.txt
- python/__init__.py
- python/receiver/gsm_wideband_input.py
As discussed in the gr-gsm group (https://groups.google.com/forum/#!topic/gr-gsm/4YiTK4WqFvs), I have created a basic hier block that can be used to channelize wideband cfiles in real time. Currently, this requires a lot of computing power, but it can be improved and optimized in the future.
> Wideband input block

- CMakeLists.txt
- lib/flow_control/burst_fnr_filter_impl.cc
- lib/flow_control/burst_sdcch_subslot_filter_impl.cc
- lib/flow_control/burst_sdcch_subslot_filter_impl.h
- lib/flow_control/burst_sdcch_subslot_splitter_impl.cc
- lib/flow_control/burst_sdcch_subslot_splitter_impl.h
- lib/receiver/clock_offset_control_impl.cc
- lib/receiver/sch.c
These changes silence a couple of compiler warnings and fix up CMakeLists.txt for OSX.
> Changes for building on OSX

- .gitignore
- apps/grgsm_decode
- apps/helpers/grgsm_capture.py
just added an option for enabling voice boundary detection in grgsm_decode, which is disabled by default. Should address issue #193
> option voice boundary detection in grgsm_decode

- apps/grgsm_livemon.grc
> Making arfcn<->freq conversions more robust for grgsm_livemon too
